-- Schema Sakila Dw
-- Dimensões: Filme, Loja, Cliente, Data, Funcionario, linguagem
use trabfinaldw_sakiladb;
show tables;

create table Date(
	Data_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DAY INT,
    MONTH INT,
    YEAR INT,
    TRIMESTRE INT,
    WEEK BOOLEAN,
    WEEKEND BOOLEAN,
    PRIMARY KEY(Data_id)
);

CREATE TABLE FILM(
	FILM_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    DEION VARCHAR(255),
    RELEASE_YEAR varchar(10),
    RENTAL_DURATION INT,
    RENTAL_RATE DOUBLE,
    ORIGINAL_LANGUAGE VARCHAR(255),
    DUBBING VARCHAR(255),
    PRIMARY KEY(FILM_ID)
);

CREATE TABLE CUSTUMER(
	CUSTUMER_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FRIST_NAME varchar(255),
    LAST_NAME varchar(255),
    FULL_NAME varchar(255),
    EMAIL VARCHAR(255),
    STATUS_ACTIVE INT,
    CREATED_DATE DATE,
    LAST_UPDATE DATE,
    PRIMARY KEY(CUSTUMER_ID)
);

CREATE TABLE STAFF(
	STAFF_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FULL_NAME varchar(255),
    EMAIL VARCHAR(255),
    PHONE INT,
    ADRESS VARCHAR(255),
    ZIP_CODE INT,
    CITY varchar(255),
    COUNTRY varchar(255),
    MANAGER BOOLEAN,
    PRIMARY KEY(STAFF_ID)
);

CREATE TABLE STORE (
	STORE_ID  SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ADRESS VARCHAR(255),
    ADDRES2 VARCHAR(255),
    DISTRICT VARCHAR(255),
    CITY VARCHAR(255),
    POSTAL_CODE VARCHAR(50),
    PHONE INT,
    LOCATION VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE LANGUAGE(
	LANGUAGE_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    LANGUAGE VARCHAR(255),
    PRIMARY KEY (LANGUAGE_ID)
);

CREATE TABLE RENTAL(
	Data_id SMALLINT UNSIGNED NOT NULL,
    STAFF_ID SMALLINT UNSIGNED NOT NULL,
    CUSTUMER_ID SMALLINT UNSIGNED NOT NULL,
    FILM_ID SMALLINT UNSIGNED NOT NULL,
    STORE_ID SMALLINT UNSIGNED NOT NULL,
    LANGUAGE_ID SMALLINT UNSIGNED NOT NULL,
    PRICE FLOAT,
    RENT_DAYS INT,
    primary key (Data_id, STAFF_ID, CUSTUMER_ID, FILM_ID, STORE_ID, LANGUAGE_ID),
    CONSTRAINT fk_Data_id FOREIGN KEY (Data_id) REFERENCES Date (Data_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT fk_STAFF_ID FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_CUSTUMER_ID FOREIGN KEY (CUSTUMER_ID) REFERENCES CUSTUMER (CUSTUMER_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_FILM_ID FOREIGN KEY (FILM_ID) REFERENCES FILM (FILM_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORE (STORE_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_LANGUAGE_ID FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);